name: flutter_clean_supabase_starter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  get_it: ^8.0.3
  supabase_flutter: ^2.9.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  google_sign_in: ^6.3.0
  app_links: ^6.4.0
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env
